Update reuse pre-commit hook
Fix the following pre-commit error:

```
$ git commit
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
codespell................................................................Passed
cmake-lint...........................................(no files to check)Skipped
cmake-format.........................................(no files to check)Skipped
Markdownlint.............................................................Passed
reuse....................................................................Failed
- hook id: reuse
- exit code: 1

Traceback (most recent call last):
  File "/Users/nathan/.cache/pre-commit/repouxck6ycy/py_env-python3/bin/reuse", line 5, in <module>
    from reuse._main import main
  File "/Users/nathan/.cache/pre-commit/repouxck6ycy/py_env-python3/lib/python3.12/site-packages/reuse/__init__.py", line 15, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

Change-Id: Ifd11cec0a5cf4f43e3c33fe3af07f58108fef49c
Reviewed-on: https://codereview.kdab.com/c/kdab/toy-renderer/+/134492
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>
Tested-by: Continuous Integration <build@kdab.com>